### ISSUE TITLE
New gems are being installed on Discourse bench.

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-docker#6]
![screenshot from 2015-03-06 17 28 58](https://cloud.githubusercontent.com/assets/4335742/6522988/570c20b0-c426-11e4-9c78-faca0bfb4f2c.png)

**Comment by tgxworld** [comment]
This means that we're potentially benchmarking a moving target.

**Comment by tgxworld** [comment]
![screenshot from 2015-04-12 20 25 55](https://cloud.githubusercontent.com/assets/4335742/7105562/414fd99e-e152-11e4-8a01-19154e850d1a.png)

**Comment by tgxworld** [comment]
@SamSaffron Discourse benchmarks have been broken for quite sometime due to changes in Ruby Trunk and breaking `json-1.8.1` gem. I think more gems might break in the future as Ruby continues to change and I'm not sure how we can resolve this. Any ideas?

**Comment by SamSaffron** [comment]
Can you do some analysis on this? We got to get it fixed, perhaps try
upgrading a few gems?

**Comment by tgxworld** [comment]
Note: Upgrading to `json 1.8.2` resolved the problem. However, `6to5-source` was yanked so there is another problem. The way to resolve would be to move Discourse's commit up.

Will continue to explore options. Perhaps we can rely on `releases` benchmarks to track regression across major versions. For per-commit benchmark, it is a little trickier since we face issues with broken gems and gems being yanked from Rubygems.org. We could probably fix this issues as we go along and only backfill 500 commits each time for Discourse benchmarks.
